### ISSUE TITLE
Už existující materiály

### ISSUE THREAD

**Issue by FilipChalupa** [Czechitas-podklady-WEB/uvod-do-js#1]
Nejsem si jistý, kam tímto repozitářem směřuješ, ale pro jistotu připomenu, že již existují částečně rozpracované materiály zde https://kodim.cz/kurzy/javascript-vyuka#uvod-do-programovani-1 (https://github.com/Czechitas-podklady-WEB/javascript-vyuka/tree/main/uvod-do-programovani-1).

**Comment by podlomar** [comment]
Jj, já vím, moc toho v nich ale není a já bych rád, kdyby to byl samostatný kurz podobné jako Úvod do programování. Takže zkombinuju co je v tom úvodu a co je v tom co jsi linkoval

**Comment by podlomar** [comment]
Materiály už jsou na dobré úrovni a vyzkoušené někoklika běhy kurzu, takže zavírám.
